ItemBlackList:
- 'item.minecraft.arrow'
- 'item.minecraft.bone'

MobBlackList:
- 'entity.minecraft.cow'
- 'entity.minecraft.villager'
- 'entity.minecraft.chicken'
- 'entity.minecraft.leash_knot'
- 'entity.minecraft.minecart'
- 'entity.minecraft.boat'