
["General Settings"]
	#Duration of the death screen in ticks (20 ticks = 1 second)
	#Range: 0 ~ 6000
	deathScreenDuration = 40
	#Whether or not to force the gamerule to respawn immediately
	forceImmediateRespawn = false

