
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# CompatStructures
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#Here you tweak how structures generate:
#  1. Kill off specific compat structures.
#  2. Control how far from spawn they can start dropping in.
#  3. Set spawn probability so your world doesn’t get spammed.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[spawn]
	# +++++++++++++++++ Hard Radius (Exclusion) +++++++++++++++++
	#Inside this radius (in blocks) nothing spawns.
	#Keeps the spawn zone clean, no mess right at world start.
	#Example: 1500 = nothing within a 1.5k block radius.
	#Range: 0 ~ 100000
	exclusion_radius = 1500
	# +++++++++++++++++ Soft Ring (Soft Radius) +++++++++++++++++
	#Outer radius of the soft ring.
	#Inside this zone, spawn chance ramps from 0% (at exclusion_radius) up to base_chance (at soft_radius).
	#Set it to 0 → soft ring disabled.
	#Example: 2500 = transition zone between 1.5k and 2.5k blocks.
	#Range: 0 ~ 100000
	soft_radius = 2500
	# +++++++++++++++++ Base Chance +++++++++++++++++
	#Max spawn chance beyond the soft_radius.
	#1.0 = always spawns, 0.35 = roughly 35% chance.
	#Lower value = rarer structures, deal with it.
	#Range: 0.0 ~ 1.0
	base_chance = 0.35

[structures]
	#Enable generation for: ad_astra
	enable_ad_astra = true
	#Enable generation for: ae2
	enable_ae2 = true
	#Enable generation for: aether
	enable_aether = true
	#Enable generation for: alexscaves
	enable_alexscaves = true
	#Enable generation for: alexsmobs
	enable_alexsmobs = true
	#Enable generation for: ars_nouveau
	enable_ars_nouveau = true
	#Enable generation for: artifacts
	enable_artifacts = true
	#Enable generation for: biomesoplenty
	enable_biomesoplenty = true
	#Enable generation for: biomeswevegone
	enable_biomeswevegone = true
	#Enable generation for: botania
	enable_botania = true
	#Enable generation for: create
	enable_create = true
	#Enable generation for: epicfight
	enable_epicfight = true
	#Enable generation for: iceandfire
	enable_iceandfire = true
	#Enable generation for: immersiveengineering
	enable_immersiveengineering = true
	#Enable generation for: irons_spellbooks
	enable_irons_spellbooks = true
	#Enable generation for: mowziesmobs
	enable_mowziesmobs = true
	#Enable generation for: naturalist
	enable_naturalist = true
	#Enable generation for: quark
	enable_quark = true
	#Enable generation for: tconstruct
	enable_tconstruct = true
	#Enable generation for: twilightforest
	enable_twilightforest = true

