
[NaturalGeneratingFeatures]
	#Enable or Disable Kopje Trees from naturally spawning (True by default)
	"Spawn Kopje Trees" = true
	#Enable or Disable Termite Mounds from naturally spawning (True by default)
	"Spawn Termite Mounds" = true

[SpawnAnimals]
	#(True by default) Enable or disable Pallas's Cat
	"Spawn Pallas's Cat" = true
	#(True by default) Enable or disable Asian Leopard Cat
	"Spawn Asian Leopard Cat" = true
	#(True by default) Enable or disable Southern Patas Monkey
	"Spawn Southern Patas Monkey" = true
	#(True by default) Enable or disable Spoonbills
	"Spawn Spoonbill" = true
	#(True by default) Enable or disable Cape Buffalo
	"Spawn Cape Buffalo" = true
	#(True by default) Enable or disable Headlight Beetle
	"Spawn Headlight Beetle" = true
	#(True by default) Enable or disable Attenborough's Echidna
	"Spawn Attenborough's Echidna" = true
	#(True by default) Enable or disable Yellow-eye Penguin
	"Spawn Yellow-eye Penguin" = true
	#(True by default) Enable or disable Northern Rockhopper Penguin
	"Spawn Northern Rockhopper" = true
	#(True by default) Enable or disable Chinstrap Penguin
	"Spawn Chinstrap Penguin" = true
	#(True by default) Enable or disable Gentoo Penguin
	"Spawn Gentoo Penguin" = true
	#(True by default) Enable or disable Chacoan Peccary
	"Spawn Chacoan Peccary" = true
	#(True by default) Enable or disable Pink Land Iguana
	"Spawn Pink Land Iguana" = true
	#(True by default) Enable or disable South Island Takahe
	"Spawn South Island Takahe" = true
	#(True by default) Enable or disable California Quail
	"Spawn California Quail" = true
	#(True by default) Enable or disable Helmeted Guineafowl
	"Spawn Helmeted Guineafowl" = true
	#(True by default) Enable or disable Marabou Stork
	"Spawn Marabou Stork" = true
	#(True by default) Enable or disable Pink Velvet Worm
	"Spawn Pink Velvet Worm" = true
	#(True by default) Enable or disable Oceanic Mantas
	"Spawn Oceanic Manta Ray" = true

