#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 02 04:33:25 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V2.9b.zip
enableShaders=false
