#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Dec 20 19:39:00 PST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=22
shaderPack=Solas Shader V3.1c.zip
enableShaders=true
