#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Dec 08 18:30:42 PST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=22
shaderPack=Solas Shader V3.0.zip
enableShaders=false
