
[performance]
	#Use async tasks for some operations to improve performance. This may cause issues with some mods.
	useAsync = true

[snowPillerAndReplacer]
	#Tick interval for snow pillers in ticks. Default is 20 (1 second).
	#Range: > 1
	tickSnowPiller = 20
	#Tick interval for snow replacer in ticks. Default is 20 (1 second).
	#Range: > 1
	tickSnowReplacer = 100

[seasonalDaylightCycle]
	#Enable seasonal daylight cycle. This will change the length of day and night based on the current season.
	enableSeasonalDaylightCycle = true
	#If true, the day and night lengths will be determined by the custom values set below. If false, the day and night lengths will be determined by the season.
	customCycleLength = false
	#Custom day length in ticks. Only used if seasonal daylight cycle is disabled.
	#Range: 0.05 ~ 100.0
	customDayLength = 1.0
	#Custom night length in ticks. Only used if seasonal daylight cycle is disabled.
	#Range: 0.05 ~ 100.0
	customNightLength = 1.0

