
[clientGeneral]
	# General client-side settings.
	# Camera effect to use under Timelapse
	#Allowed Values: SurfaceOrbit, SurfaceRotation, None
	timelapseCameraType = "SurfaceOrbit"
	# Screen dim to use under Timelapse. The default value of 0 will remove the screen dim.
	#Range: 0 ~ 100
	timelapseDimValue = 0
	# If enabled, pressing enter on In Bed Chat Screen with zero chat text will also function as Sleep button.
	# Requires bedRestEnabled in server config, otherwise does nothing otherwise.
	bedRestWithChatEnter = false
	# [1.19.4+ only] Enhances/fixes keyboard-navigation issues on the In-Bed chat screen. Summary:
	# - Allows to re-focus the chat box by clicking on it;
	# - Prevents arrow keys from changing focus away from chat box, use Ctrl+Tab to change focus instead;
	# - Prevents ENTER from sending a chat message unless the chat box is actually focused;
	# - Allows ENTER to actually work if one of the buttons is focused instead of the chat box.
	# You will probably want to keep this enabled because of the buttons we add to the screen, but it can be disabled in case there are mod conflicts.
	inBedChatFixes = true

