ancientPotMaxParticleCount = 24
ancientPotMaxDropCount = 10
ancientBrazierEntities = ["wetland_whimsy:swamp_spider", "wetland_whimsy:blemish", "minecraft:zombie", "minecraft:skeleton", "minecraft:spider", "minecraft:cave_spider", "minecraft:drowned"]
disableVanillaSwampHuts = true
upgradeDisks = true
