Header: '§a[FancyClear] '
Command:
  Reload: 'Re-read the configuration file.'
  Kill: 'Execute the delete entity command.'
  SaveID: 'Save entity name to entity-id-list.yml.'
  TPS: 'TPS:{tps}'
Clear:
  30: 'After §f30 §aseconds, the entity will be cleaned up.'
  10: 'After §f10 §aseconds, the entity will be cleaned up.'
  5: 'After §f5 §aseconds, the entity will be cleaned up.'
  4: 'After §f4 §aseconds, the entity will be cleaned up.'
  3: 'After §f3 §aseconds, the entity will be cleaned up.'
  2: 'After §f2 §aseconds, the entity will be cleaned up.'
  1: 'After §f1 §aseconds, the entity will be cleaned up.'
  remove: 'Clear §f{mob} §acreatures and §f{item} §aitem.'
