Header: '§[FancyClear] '
Command:
  Reload: 'a구성 파일을 다시 읽으십시오.'
  Kill: '엔티티 삭제 명령을 실행합니다.'
  SaveID: '엔티티 이름을 entity-id-list.yml에 저장합니다.'
  TPS: 'TPS:{tps}'
Clear:
  30: '§f30§a초 후에 엔터티가 정리됩니다.'
  10: '§f10§a초 후에 엔티티가 정리됩니다.'
  5: '§f5§a초 후에 엔티티가 정리됩니다.'
  4: '§f4§a초 후에 엔티티가 정리됩니다.'
  3: '§f3§a초 후에 엔티티가 정리됩니다.'
  2: '§f2§a초 후에 엔티티가 정리됩니다.'
  1: '§f1§a초 후에 엔티티가 정리됩니다.'
  remove: '§f{mob}§a개의 크리처와 §f{item}§a개의 아이템을 클리어하세요.'
