Header: '§a[FancyClear] '
Command:
  Reload: 'Leia novamente o arquivo de configuração.'
  Kill: 'Execute o comando delete entity.'
  SaveID: 'Salve o nome da entidade em entity-id-list.yml.'
  TPS: 'TPS:{tps}'
Clear:
  30: 'Após §f30 §asegundos, a entidade será limpa.'
  10: 'Após §f10 §asegundos, a entidade será limpa.'
  5: 'Após §f5 §asegundos, a entidade será limpa.'
  4: 'Após §f4 §asegundos, a entidade será limpa.'
  3: 'Após §f3 §asegundos, a entidade será limpa.'
  2: 'Após §f2 §asegundos, a entidade será limpa.'
  1: 'Após §f1 §asegundos, a entidade será limpa.'
  remove: 'Elimine §f{mob} §acriaturas e §f{item} §aitens.'
